[package]
name = "silverutil"
version = "0.1.0"
edition = "2021"

[dependencies]
silverlib = { path = "../../" }
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
